#!/usr/bin/env bash

commit_message=$(cat "$1")
commit_style='^((feat|docs|fix|perf|refactor|style|test|chore)( )?(\(.+\))?:( )?(#[0-9]*( )?)*.{5,50}|Initial commit)'

[[ "$commit_message" =~ $commit_style ]] || {
  echo 'Commit message does not follow the style convention!'
  exit 1
}
